# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Docker Action
        uses: mr-smithers-excellent/docker-build-push@v2
        with:
          image: wndrr/websites/so-many-days-left
          tag: latest
          registry: registry.gitlab.com
          dockerfile: Dockerfile
          username: Wndrr
          password: ${{ secrets.Gitlab }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 167.99.197.153
        username: ${{ secrets.SshUsername }}
        password: ${{ secrets.SshPassword }}
        port: 22
        script: docker stop SoManyDaysLeft || true;docker rm SoManyDaysLeft || true; docker pull registry.gitlab.com/wndrr/websites/SoManyDaysLeft; docker run --name=SoManyDaysLeft -d -e VIRTUAL_HOST=SoManyDaysLeft.viales.fr -p 7432:80 registry.gitlab.com/wndrr/websites/so-many-days-left          
